name: Deploy Status

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Deployment
        uses: chrby/deployment-action@v2
        with:
          token: "${{ github.token }}"
          environment-url: "https://sellify-multivendor-hub.onrender.com"
          environment: production
          initial-status: success
